# Step 1: 套件匯入

In [38]:
import pandas as pd
import numpy as np
import math
import csv

from FinMind.data import DataLoader
import talib

from mplfinance.original_flavor import candlestick_ohlc
import matplotlib.dates as mpl_dates
import matplotlib.pyplot as plt

from datetime import datetime
from io import StringIO
import pprint as pp

# Step 2: 資料引入

使用 FinMind 套件獲取資料

## 1. 股價日成交資訊

In [39]:
api_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRlIjoiMjAyMS0xMi0yNyAxNDo1OTowOSIsInVzZXJfaWQiOiJkdXJhbnQ3MTA5MTYiLCJpcCI6IjE0MC4xMjAuMTMuMjMwIn0.8-KIC3-OA4D6JcOtQ_fJBOVkyugx60t1Gy82c57TLz4"

api = DataLoader()
api.login_by_token(api_token = api_token)

# 設定股票標的和開始/結束日期
#stock_id = "2454"
stock_id = "2002"
#start_date='2011-12-05'
start_date='2012-11-14'
end_date='2020-12-31'

# 股價日成交資訊
TaiwanStockPriceDay = api.taiwan_stock_daily(
    stock_id = stock_id,
    start_date = start_date,
    end_date = end_date
)

TaiwanStockPriceDay

,date,stock_id,Trading_Volume,Trading_money,open,max,min,close,spread,Trading_turnover
0,2012-11-14,2002,9019944,225213360,24.95,25.10,24.85,25.10,0.15,3778
1,2012-11-15,2002,11575388,288529193,25.00,25.05,24.70,25.00,-0.10,4927
2,2012-11-16,2002,13076660,324966600,25.00,25.05,24.75,24.80,-0.20,5489
3,2012-11-19,2002,10426880,259817300,24.80,25.00,24.80,24.95,0.15,3837
4,2012-11-20,2002,9441485,235686025,25.00,25.05,24.90,24.95,0.00,3435
...,...,...,...,...,...,...,...,...,...,...
1991,2020-12-25,2002,37793792,913514566,24.35,24.45,24.00,24.20,-0.15,10164
1992,2020-12-28,2002,22448980,543624840,24.20,24.30,24.05,24.30,0.10,7038
1993,2020-12-29,2002,36190388,889836145,24.50,24.75,24.45,24.65,0.35,11966
1994,2020-12-30,2002,62189405,1551538041,24.80,25.15,24.70,25.00,0.35,17828
1995,2020-12-31,2002,26965560,668379342,25.00,25.00,24.65,24.75,-0.25,6919

## 2. 融資融券表

In [40]:
# 融資融券表
TaiwanStockMarginPurchaseShortSale = api.taiwan_stock_margin_purchase_short_sale(
    stock_id = stock_id,
    start_date = start_date,
    end_date = end_date
)

TaiwanStockMarginPurchaseShortSale

,date,stock_id,MarginPurchaseBuy,MarginPurchaseCashRepayment,MarginPurchaseLimit,MarginPurchaseSell,MarginPurchaseTodayBalance,MarginPurchaseYesterdayBalance,Note,OffsetLoanAndShort,ShortSaleBuy,ShortSaleCashRepayment,ShortSaleLimit,ShortSaleSell,ShortSaleTodayBalance,ShortSaleYesterdayBalance
0,2012-11-14,2002,122,0,3818119,148,16488,16514,,118,45,0,3818119,69,12328,12304
1,2012-11-15,2002,122,1,3818119,206,16403,16488,,122,156,2,3818119,118,12288,12328
2,2012-11-16,2002,191,0,3818119,152,16442,16403,,37,103,0,3818119,11,12196,12288
3,2012-11-19,2002,68,3,3818119,162,16345,16442,,13,16,0,3818119,49,12229,12196
4,2012-11-20,2002,426,0,3818119,222,16549,16345,,35,55,0,3818119,96,12270,12229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1991,2020-12-25,2002,1240,0,3933715,1211,21171,21142,,10,9,0,3933715,2,435,442
1992,2020-12-28,2002,384,2,3933715,1744,19809,21171,,0,8,0,3933715,10,437,435
1993,2020-12-29,2002,1743,2,3933715,1483,20067,19809,,3,27,0,3933715,21,431,437
1994,2020-12-30,2002,3286,0,3933715,2394,20959,20067,,26,9,0,3933715,11,433,431
1995,2020-12-31,2002,247,5,3933715,1702,19499,20959,,0,13,0,3933715,10,430,433

## 3. 法人買賣表

In [41]:
# 法人買賣表
TaiwanStockInstitutionalInvestorsBuySell = api.taiwan_stock_institutional_investors(
    stock_id = stock_id,
    start_date = start_date,
    end_date = end_date
)

TaiwanStockInstitutionalInvestorsBuySell

            date stock_id       buy                 name      sell
0     2012-11-14     2002   1493000     Foreign_Investor   4951000
1     2012-11-14     2002    267000     Investment_Trust     30000
2     2012-11-14     2002    570000               Dealer    321000
3     2012-11-15     2002   3133000     Foreign_Investor   7501000
4     2012-11-15     2002    275000     Investment_Trust     85000
...          ...      ...       ...                  ...       ...
8233  2020-12-31     2002  15387000     Foreign_Investor  12639858
8234  2020-12-31     2002         0  Foreign_Dealer_Self         0
8235  2020-12-31     2002     40000     Investment_Trust         0
8236  2020-12-31     2002    746000          Dealer_self    613000
8237  2020-12-31     2002     12000       Dealer_Hedging     72000

[8238 rows x 5 columns]

## 4. 加權指數

In [42]:
TaiwanStockTotalReturnIndex = api.taiwan_stock_total_return_index(
    index_id="TAIEX",
    start_date = start_date,
    end_date = end_date
)

TaiwanStockTotalReturnIndex

         price index_id        date
0     10275.50    TAIEX  2012-11-14
1     10252.65    TAIEX  2012-11-15
2     10232.89    TAIEX  2012-11-16
3     10231.42    TAIEX  2012-11-19
4     10255.43    TAIEX  2012-11-20
...        ...      ...         ...
1991  27667.00    TAIEX  2020-12-25
1992  27959.77    TAIEX  2020-12-28
1993  27938.50    TAIEX  2020-12-29
1994  28354.81    TAIEX  2020-12-30
1995  28441.36    TAIEX  2020-12-31

[1996 rows x 3 columns]

# Step 3: 建立具體Input資料

## 1. 日線標準化

In [46]:
# Start Date 20
# TaiwanStockPriceDay.iloc[i+14:i+34]
# 移動式正規化
# min: 0.2 max: 0.8

pp.pprint(TaiwanStockPriceDay.iloc[14:34])
piece = TaiwanStockPriceDay.iloc[14:34][['open', 'max', 'min', 'close','Trading_Volume']]
max_value = 0.8
min_value = 0.2

Max_Volume = piece['Trading_Volume'].max()
Min_Volume = piece['Trading_Volume'].min()
Max_Price = piece['max'].max()
Min_Price = piece['min'].min()
print(Max_Price, Min_Price)


piece['max'] = min_value + (max_value - min_value) * (piece['max'] - Min_Price) / (Max_Price - Min_Price)
piece['min'] = min_value + (max_value - min_value) * (piece['min'] - Min_Price) / (Max_Price - Min_Price)
piece['open'] = min_value + (max_value - min_value) * (piece['open'] - Min_Price) / (Max_Price - Min_Price)
piece['close'] = min_value + (max_value - min_value) * (piece['close'] - Min_Price) / (Max_Price - Min_Price)
piece['Trading_Volume'] = min_value + (max_value - min_value) * (piece['Trading_Volume'] - Min_Volume) / (Max_Volume - Min_Volume)
pp.pprint(piece)

          date stock_id  Trading_Volume  Trading_money   open    max    min  \
14  2012-12-04     2002        20711913      537157482  26.05  26.20  25.70
15  2012-12-05     2002        24445487      641473631  26.20  26.45  25.90
16  2012-12-06     2002        17804251      466079886  26.40  26.40  26.05
17  2012-12-07     2002        10769251      282449105  26.30  26.30  26.10
18  2012-12-10     2002        12887966      336992199  26.30  26.30  26.10
19  2012-12-11     2002        23574292      614815704  26.10  26.20  25.90
20  2012-12-12     2002        27487452      724325068  26.25  26.50  26.15
21  2012-12-13     2002        31802337      839450881  26.30  26.55  26.30
22  2012-12-14     2002        20623024      544771823  26.45  26.50  26.30
23  2012-12-17     2002        20584862      543056595  26.50  26.50  26.30
24  2012-12-18     2002        19886584      519888080  26.50  26.50  26.20
25  2012-12-19     2002        19160902      505425105  26.40  26.45  26.30
26  2012-12-20     2002        14034674      369347448  26.40  26.45  26.15
27  2012-12-21     2002        19854886      521672469  26.35  26.45  26.15
28  2012-12-22     2002         6594783      173046782  26.25  26.40  26.20
29  2012-12-24     2002         6322637      165967669  26.20  26.35  26.15
30  2012-12-25     2002         8789002      231765538  26.25  26.50  26.15
31  2012-12-26     2002        58059723     1579191445  26.50  27.45  26.50
32  2012-12-27     2002        25520597      694561447  27.40  27.40  27.05
33  2012-12-28     2002        22223594      607643922  27.45  27.45  27.20

    close  spread  Trading_turnover
14  26.20   -0.05              6613
15  26.40    0.20              6312
16  26.30   -0.10              5079
17  26.30    0.00              3603
18  26.10   -0.20              3585
19  26.20    0.10              5562
20  26.30    0.10              5873
21  26.45    0.15              6769
22  26.50    0.05              5517
23  26.50    0.00              6554
24  26.35   -0.15              5187
25  26.45    0.10              4747
26  26.45    0.00              4185
27  26.45    0.00              5435
28  26.25   -0.20              2107
29  26.25    0.00              2489
30  26.45    0.20              3541
31  27.40    0.95             18100
32  27.30   -0.10              8199
33  27.35    0.05              7132
27.45 25.7
        open       max       min     close  Trading_Volume
14  0.320000  0.371429  0.200000  0.371429        0.366874
15  0.371429  0.457143  0.268571  0.440000        0.410172
16  0.440000  0.440000  0.320000  0.405714        0.333153
17  0.405714  0.405714  0.337143  0.405714        0.251568
18  0.405714  0.405714  0.337143  0.337143        0.276139
19  0.337143  0.371429  0.268571  0.371429        0.400069
20  0.388571  0.474286  0.354286  0.405714        0.445450
21  0.405714  0.491429  0.405714  0.457143        0.495491
22  0.457143  0.474286  0.405714  0.474286        0.365843
23  0.474286  0.474286  0.405714  0.474286        0.365400
24  0.474286  0.474286  0.371429  0.422857        0.357302
25  0.440000  0.457143  0.405714  0.457143        0.348887
26  0.440000  0.457143  0.354286  0.457143        0.289437
27  0.422857  0.457143  0.354286  0.457143        0.356935
28  0.388571  0.440000  0.371429  0.388571        0.203156
29  0.371429  0.422857  0.354286  0.388571        0.200000
30  0.388571  0.474286  0.354286  0.457143        0.228603
31  0.474286  0.800000  0.474286  0.782857        0.800000
32  0.782857  0.782857  0.662857  0.748571        0.422641
33  0.800000  0.800000  0.714286  0.765714        0.384405

## 2. 技術指標

* RSI 14
* EMA 10

In [48]:
piece['RSI'] = talib.RSI(TaiwanStockPriceDay.iloc[0:34]['close'], timeperiod=14)[14:]/100
piece['EMA'] = talib.EMA(TaiwanStockPriceDay.iloc[0:34]['close'], timeperiod=10)[14:]
piece['EMA'] = min_value + (max_value - min_value) * (piece['EMA'] - Min_Price) / (Max_Price - Min_Price)

#df = pd.Series.rolling(TaiwanStockPriceDay.iloc[0:34]['close'], window=6).mean()[14:]
#piece['BIAS'] = (TaiwanStockPriceDay.iloc[14:34]['close'] - df )/df
piece['OBV'] = talib.OBV(TaiwanStockPriceDay.iloc[14:34]['close'], TaiwanStockPriceDay.iloc[14:34]['Trading_Volume'])
Max_OBV = piece['OBV'].max()
Min_OBV = piece['OBV'].min()
piece['OBV'] = min_value + (max_value - min_value) * (piece['OBV'] - Min_OBV) / (Max_OBV - Min_OBV)

Max_TAIEX = TaiwanStockTotalReturnIndex[14:34]['price'].max()
Min_TAIEX = TaiwanStockTotalReturnIndex[14:34]['price'].min()
piece['TAIEX'] = min_value + (max_value - min_value) * (TaiwanStockTotalReturnIndex[0:34]['price'] - Min_TAIEX) / (Max_TAIEX - Min_TAIEX)
piece

,open,max,min,close,Trading_Volume,RSI,EMA,OBV,TAIEX
14,0.320000,0.371429,0.200000,0.371429,0.366874,0.703704,0.255147,0.222992,0.405083
15,0.371429,0.457143,0.268571,0.440000,0.410172,0.725594,0.288757,0.312967,0.526680
16,0.440000,0.440000,0.320000,0.405714,0.333153,0.697833,0.310022,0.247436,0.461439
17,0.405714,0.405714,0.337143,0.405714,0.251568,0.697833,0.327420,0.247436,0.509510
18,0.405714,0.405714,0.337143,0.337143,0.276139,0.640954,0.329188,0.200000,0.426606
19,0.337143,0.371429,0.268571,0.371429,0.400069,0.656049,0.336868,0.286768,0.437218
20,0.388571,0.474286,0.354286,0.405714,0.445450,0.670948,0.349386,0.387940,0.630755
21,0.405714,0.491429,0.405714,0.457143,0.495491,0.692467,0.368978,0.504992,0.800000
22,0.457143,0.474286,0.405714,0.474286,0.365843,0.699522,0.388125,0.580898,0.652472
23,0.474286,0.474286,0.405714,0.474286,0.365400,0.699522,0.403790,0.580898,0.481711
24,0.474286,0.474286,0.371429,0.422857,0.357302,0.647821,0.407257,0.507703,0.513230
25,0.440000,0.457143,0.405714,0.457143,0.348887,0.665567,0.416327,0.578227,0.598584
26,0.440000,0.457143,0.354286,0.457143,0.289437,0.665567,0.423748,0.578227,0.391104
27,0.422857,0.457143,0.354286,0.457143,0.356935,0.665567,0.429820,0.578227,0.200000
28,0.388571,0.440000,0.371429,0.388571,0.203156,0.591159,0.422320,0.553954,0.251156
29,0.371429,0.422857,0.354286,0.388571,0.200000,0.591159,0.416184,0.553954,0.239451
30,0.388571,0.474286,0.354286,0.457143,0.228603,0.638084,0.423631,0.586303,0.495108
31,0.474286,0.800000,0.474286,0.782857,0.800000,0.771967,0.488945,0.800000,0.489097
32,0.782857,0.782857,0.662857,0.748571,0.422641,0.740898,0.536150,0.706068,0.525076
33,0.800000,0.800000,0.714286,0.765714,0.384405,0.746394,0.577889,0.787865,0.654323

## 3. 籌碼面
### 1. 融資融券表

In [37]:
# MarginPurchaseTodayBalance
# MarginPurchaseBuy - MarginPurchaseSell - MarginPurchaseCashRepayment
# ShortSaleTodayBalance 
# ShortSaleBuy - ShortSaleSell -ShortSaleCashRepayment

# TaiwanStockMarginPurchaseShortSale['MarginIncrease'] = TaiwanStockMarginPurchaseShortSale['MarginPurchaseBuy'] - TaiwanStockMarginPurchaseShortSale['MarginPurchaseSell'] - TaiwanStockMarginPurchaseShortSale['MarginPurchaseCashRepayment']


# TaiwanStockMarginPurchaseShortSale[14:34][['MarginPurchaseTodayBalance', 'ShortSaleTodayBalance']]

#MarginMax = TaiwanStockMarginPurchaseShortSale['MarginPurchaseTodayBalance'].max()
#ShortMax = TaiwanStockMarginPurchaseShortSale['ShortSaleTodayBalance'].max()
#piece['MarginPurchaseTodayBalance'] = (TaiwanStockMarginPurchaseShortSale['MarginPurchaseTodayBalance']/MarginMax)[14:34]
#piece['ShortSaleTodayBalance'] = (TaiwanStockMarginPurchaseShortSale['ShortSaleTodayBalance']/ShortMax)[14:34]

over_bought_sold = []

for t in TaiwanStockPriceDay['date']:
    filt = (TaiwanStockInstitutionalInvestorsBuySell['date'] == t)
    diff = sum(TaiwanStockInstitutionalInvestorsBuySell.loc[filt]['buy']) - sum(TaiwanStockInstitutionalInvestorsBuySell.loc[filt]['sell'])    
    over_bought_sold.append(diff)

TaiwanStockPriceDay['ratio'] = TaiwanStockMarginPurchaseShortSale['ShortSaleTodayBalance'] / TaiwanStockMarginPurchaseShortSale['MarginPurchaseTodayBalance'][14:34]
TaiwanStockPriceDay['diff'] = np.array(over_bought_sold)

piece['RGZRATIO'] = TaiwanStockPriceDay['ratio']

piece

,open,max,min,close,Trading_Volume,RSI,EMA,TAIEX,RGZRATIO
14,0.320000,0.371429,0.200000,0.371429,0.366874,0.703704,0.255147,0.405083,0.800898
15,0.371429,0.457143,0.268571,0.440000,0.410172,0.725594,0.288757,0.526680,0.815184
16,0.440000,0.440000,0.320000,0.405714,0.333153,0.697833,0.310022,0.461439,0.791318
17,0.405714,0.405714,0.337143,0.405714,0.251568,0.697833,0.327420,0.509510,0.803998
18,0.405714,0.405714,0.337143,0.337143,0.276139,0.640954,0.329188,0.426606,0.806767
19,0.337143,0.371429,0.268571,0.371429,0.400069,0.656049,0.336868,0.437218,0.822677
20,0.388571,0.474286,0.354286,0.405714,0.445450,0.670948,0.349386,0.630755,0.822278
21,0.405714,0.491429,0.405714,0.457143,0.495491,0.692467,0.368978,0.800000,0.752512
22,0.457143,0.474286,0.405714,0.474286,0.365843,0.699522,0.388125,0.652472,0.752629
23,0.474286,0.474286,0.405714,0.474286,0.365400,0.699522,0.403790,0.481711,0.743224
24,0.474286,0.474286,0.371429,0.422857,0.357302,0.647821,0.407257,0.513230,0.737027
25,0.440000,0.457143,0.405714,0.457143,0.348887,0.665567,0.416327,0.598584,0.748730
26,0.440000,0.457143,0.354286,0.457143,0.289437,0.665567,0.423748,0.391104,0.740909
27,0.422857,0.457143,0.354286,0.457143,0.356935,0.665567,0.429820,0.200000,0.708683
28,0.388571,0.440000,0.371429,0.388571,0.203156,0.591159,0.422320,0.251156,0.615964
29,0.371429,0.422857,0.354286,0.388571,0.200000,0.591159,0.416184,0.239451,0.612257
30,0.388571,0.474286,0.354286,0.457143,0.228603,0.638084,0.423631,0.495108,0.629192
31,0.474286,0.800000,0.474286,0.782857,0.800000,0.771967,0.488945,0.489097,0.505104
32,0.782857,0.782857,0.662857,0.748571,0.422641,0.740898,0.536150,0.525076,0.500059
33,0.800000,0.800000,0.714286,0.765714,0.384405,0.746394,0.577889,0.654323,0.513601

### 2. 法人買賣表

In [9]:
dateArray = TaiwanStockPriceDay['date']

#Foreign_Investor = TaiwanStockInstitutionalInvestorsBuySell.loc[TaiwanStockInstitutionalInvestorsBuySell['name'] == 'Foreign_Investor']
#Foreign_Dealer_Self = TaiwanStockInstitutionalInvestorsBuySell.loc[TaiwanStockInstitutionalInvestorsBuySell['name'] == 'Foreign_Dealer_Self']
#Investment_Trust = TaiwanStockInstitutionalInvestorsBuySell.loc[TaiwanStockInstitutionalInvestorsBuySell['name'] == 'Investment_Trust']
#Dealer = TaiwanStockInstitutionalInvestorsBuySell.loc[TaiwanStockInstitutionalInvestorsBuySell['name'] == 'Dealer']
#Dealer_self = TaiwanStockInstitutionalInvestorsBuySell.loc[TaiwanStockInstitutionalInvestorsBuySell['name'] == 'Dealer_self']
#Dealer_Hedging = TaiwanStockInstitutionalInvestorsBuySell.loc[TaiwanStockInstitutionalInvestorsBuySell['name'] == 'Dealer_Hedging']

#Foreign_Investor # 1999 2012-11-14~2020-12-31
#Foreign_Dealer_Self #746 2017-12-18~2020-12-31
#Investment_Trust # 1999 2012-11-14~2020-12-31

# Dealer # 504 2012-11-14~2014-11-28
# Dealer_self #1495 2014-12-01~2020-12-31
# Dealer_Hedging

#temp = TaiwanStockInstitutionalInvestorsBuySell.loc[TaiwanStockInstitutionalInvestorsBuySell['name'] == 'Foreign_Investor'].loc[TaiwanStockInstitutionalInvestorsBuySell['date']>=dateArray[14]].loc[TaiwanStockInstitutionalInvestorsBuySell['date']<dateArray[34]]
#temp


Foreign_Investor = TaiwanStockInstitutionalInvestorsBuySell.loc[TaiwanStockInstitutionalInvestorsBuySell['name'] == 'Foreign_Investor']
Investment_Trust = TaiwanStockInstitutionalInvestorsBuySell.loc[TaiwanStockInstitutionalInvestorsBuySell['name'] == 'Investment_Trust']

for d in set(Foreign_Investor['date']) - set(dateArray):
    Foreign_Investor = Foreign_Investor.drop(Foreign_Investor[Foreign_Investor['date'] == d].index)
    Investment_Trust = Investment_Trust.drop(Investment_Trust[Investment_Trust['date'] == d].index)

Foreign_Investor = Foreign_Investor.reset_index()
Investment_Trust = Investment_Trust.reset_index()

def get_max(buy, sell):
    if buy > sell:
        return buy 
    else:
        return sell

ForeignInvestorMax = get_max(Foreign_Investor['buy'].max(), Foreign_Investor['sell'].max())
InvestmentTrustMax = get_max(Investment_Trust['buy'].max(), Investment_Trust['sell'].max())

Foreign_Investor['buy'] = Foreign_Investor['buy']/ForeignInvestorMax
Foreign_Investor['sell'] = Foreign_Investor['sell']/ForeignInvestorMax
Investment_Trust['buy'] = Investment_Trust['buy']/InvestmentTrustMax
Investment_Trust['sell'] = Investment_Trust['sell']/InvestmentTrustMax



piece['ForeignBuy'] = Foreign_Investor['buy'][14:34]
piece['ForeignSell'] = Foreign_Investor['sell'][14:34]
piece['TrustBuy'] = Investment_Trust['buy'][14:34]
piece['TrustSell'] = Investment_Trust['sell'][14:34]
piece

,open,max,min,close,Trading_Volume,RSI,EMA,MarginPurchaseTodayBalance,ShortSaleTodayBalance,ForeignBuy,ForeignSell,TrustBuy,TrustSell
14,0.4875,0.5250,0.2875,0.4500,0.599061,0.744000,0.287843,0.438358,0.859368,0.121258,0.230636,0.009865,0.044229
15,0.2000,0.5125,0.2000,0.4875,0.800000,0.750450,0.324144,0.439413,0.868537,0.229137,0.265830,0.089444,0.112627
16,0.4500,0.4875,0.3875,0.4500,0.488928,0.730626,0.347027,0.438437,0.869311,0.176722,0.153516,0.000000,0.019073
17,0.5125,0.6875,0.5125,0.6375,0.530486,0.764171,0.399841,0.397905,0.978458,0.158701,0.105440,0.020059,0.023841
18,0.6125,0.6250,0.4375,0.4375,0.458610,0.668538,0.406688,0.421417,0.927419,0.134040,0.162746,0.016113,0.167215
19,0.5375,0.6625,0.4625,0.6625,0.571374,0.712177,0.453199,0.390279,0.990720,0.219450,0.160150,0.034528,0.013482
20,0.6625,0.6875,0.5250,0.6750,0.589825,0.714427,0.493526,0.363521,1.000000,0.227968,0.220290,0.157678,0.099145
21,0.6625,0.8000,0.6125,0.7750,0.627934,0.732442,0.544703,0.427644,0.993151,0.208328,0.181035,0.071194,0.006741
22,0.6500,0.7000,0.5625,0.6750,0.495960,0.685847,0.568394,0.413157,0.990278,0.168009,0.149670,0.037817,0.006906
23,0.4250,0.5875,0.4000,0.5000,0.640941,0.612423,0.555959,0.431154,0.905546,0.200752,0.258602,0.137290,0.090595
24,0.2500,0.4625,0.2500,0.4625,0.511122,0.597658,0.538966,0.452634,0.881352,0.154821,0.195729,0.027129,0.014633
25,0.4625,0.5375,0.4000,0.5375,0.424372,0.617519,0.538700,0.441814,0.890411,0.149924,0.124851,0.089115,0.063302
26,0.3875,0.4875,0.2625,0.3750,0.512115,0.553737,0.508936,0.443714,0.860252,0.142888,0.154873,0.039461,0.095857
27,0.2625,0.4375,0.2000,0.2250,0.503339,0.502176,0.457311,0.450259,0.824127,0.126015,0.170804,0.112463,0.087800
28,0.3375,0.4000,0.2500,0.3375,0.200000,0.536998,0.435527,0.432209,0.834401,0.007715,0.000125,0.117396,0.008385
29,0.3750,0.4250,0.2625,0.2750,0.301586,0.515427,0.406341,0.435798,0.826889,0.070973,0.046722,0.063959,0.052779
30,0.3750,0.5375,0.3250,0.4375,0.287670,0.564418,0.412006,0.414608,0.827994,0.060787,0.011201,0.098323,0.009372
31,0.4375,0.5375,0.3750,0.3750,0.242224,0.541732,0.405278,0.394738,0.827000,0.047755,0.015727,0.072016,0.035021
32,0.4000,0.4625,0.3125,0.3250,0.381983,0.523601,0.390682,0.413183,0.816836,0.102843,0.080476,0.077770,0.050970
33,0.4750,0.5000,0.3625,0.5000,0.399246,0.576967,0.410558,0.401151,0.810208,0.119901,0.058109,0.118711,0.152581

In [10]:
test = piece.values.flatten()
test

array([4.87500000e-01, 5.25000000e-01, 2.87500000e-01, 4.50000000e-01,
       5.99060581e-01, 7.44000000e-01, 2.87843276e-01, 4.38357610e-01,
       8.59368095e-01, 1.21258390e-01, 2.30636287e-01, 9.86517593e-03,
       4.42288721e-02, 2.00000000e-01, 5.12500000e-01, 2.00000000e-01,
       4.87500000e-01, 8.00000000e-01, 7.50449910e-01, 3.24144499e-01,
       4.39413131e-01, 8.68537340e-01, 2.29137087e-01, 2.65829623e-01,
       8.94442618e-02, 1.12627425e-01, 4.50000000e-01, 4.87500000e-01,
       3.87500000e-01, 4.50000000e-01, 4.88928413e-01, 7.30625814e-01,
       3.47027317e-01, 4.38436774e-01, 8.69310650e-01, 1.76721902e-01,
       1.53516467e-01, 0.00000000e+00, 1.90726735e-02, 5.12500000e-01,
       6.87500000e-01, 5.12500000e-01, 6.37500000e-01, 5.30486437e-01,
       7.64170552e-01, 3.99840532e-01, 3.97904792e-01, 9.78457799e-01,
       1.58701302e-01, 1.05439842e-01, 2.00591911e-02, 2.38408418e-02,
       6.12500000e-01, 6.25000000e-01, 4.37500000e-01, 4.37500000e-01,
       4.58610393e-01, 6.68537579e-01, 4.06687708e-01, 4.21416508e-01,
       9.27419355e-01, 1.34039909e-01, 1.62745936e-01, 1.61131207e-02,
       1.67214732e-01, 5.37500000e-01, 6.62500000e-01, 4.62500000e-01,
       6.62500000e-01, 5.71374163e-01, 7.12177094e-01, 4.53199034e-01,
       3.90278657e-01, 9.90720283e-01, 2.19449719e-01, 1.60150197e-01,
       3.45281158e-02, 1.34824071e-02, 6.62500000e-01, 6.87500000e-01,
       5.25000000e-01, 6.75000000e-01, 5.89824869e-01, 7.14426541e-01,
       4.93526482e-01, 3.63521216e-01, 1.00000000e+00, 2.27967994e-01,
       2.20289926e-01, 1.57678395e-01, 9.91450181e-02, 6.62500000e-01,
       8.00000000e-01, 6.12500000e-01, 7.75000000e-01, 6.27934035e-01,
       7.32441905e-01, 5.44703486e-01, 4.27644079e-01, 9.93150685e-01,
       2.08327899e-01, 1.81034707e-01, 7.11936863e-02, 6.74120355e-03,
       6.50000000e-01, 7.00000000e-01, 5.62500000e-01, 6.75000000e-01,
       4.95960259e-01, 6.85847130e-01, 5.68393761e-01, 4.13157061e-01,
       9.90278392e-01, 1.68008814e-01, 1.49670179e-01, 3.78165077e-02,
       6.90562315e-03, 4.25000000e-01, 5.87500000e-01, 4.00000000e-01,
       5.00000000e-01, 6.40940841e-01, 6.12423083e-01, 5.55958532e-01,
       4.31153684e-01, 9.05545736e-01, 2.00751910e-01, 2.58602445e-01,
       1.37290365e-01, 9.05951989e-02, 2.50000000e-01, 4.62500000e-01,
       2.50000000e-01, 4.62500000e-01, 5.11122352e-01, 5.97657810e-01,
       5.38966071e-01, 4.52633523e-01, 8.81352187e-01, 1.54820576e-01,
       1.95728556e-01, 2.71292338e-02, 1.46333443e-02, 4.62500000e-01,
       5.37500000e-01, 4.00000000e-01, 5.37500000e-01, 4.24371780e-01,
       6.17519401e-01, 5.38699513e-01, 4.41814440e-01, 8.90410959e-01,
       1.49924199e-01, 1.24851389e-01, 8.91154226e-02, 6.33015455e-02,
       3.87500000e-01, 4.87500000e-01, 2.62500000e-01, 3.75000000e-01,
       5.12115255e-01, 5.53737273e-01, 5.08935965e-01, 4.43714376e-01,
       8.60251878e-01, 1.42888494e-01, 1.54872764e-01, 3.94607037e-02,
       9.58566261e-02, 2.62500000e-01, 4.37500000e-01, 2.00000000e-01,
       2.25000000e-01, 5.03339131e-01, 5.02175646e-01, 4.57311244e-01,
       4.50258602e-01, 8.24127265e-01, 1.26014909e-01, 1.70804209e-01,
       1.12463006e-01, 8.78000658e-02, 3.37500000e-01, 4.00000000e-01,
       2.50000000e-01, 3.37500000e-01, 2.00000000e-01, 5.36997519e-01,
       4.35527382e-01, 4.32209204e-01, 8.34401237e-01, 7.71533297e-03,
       1.25184736e-04, 1.17395594e-01, 8.38539954e-03, 3.75000000e-01,
       4.25000000e-01, 2.62500000e-01, 2.75000000e-01, 3.01586379e-01,
       5.15427251e-01, 4.06340585e-01, 4.35797973e-01, 8.26889085e-01,
       7.09731569e-02, 4.67222973e-02, 6.39592239e-02, 5.27786912e-02,
       3.75000000e-01, 5.37500000e-01, 3.25000000e-01, 4.37500000e-01,
       2.87669645e-01, 5.64417709e-01, 4.12005933e-01, 4.14608402e-01,
       8.27993814e-01, 6.07870725e-02, 1.12007396e-02, 9.83229201e-02,
       9.37191713e-03, 4.37500000e-01, 5.37500000e-01, 3.75000000e-01,
       3.75000000e-01, 2.42223629e-01, 5.41732202e-01, 4.05277582e-01,
       3.94738231e-01, 8.26999558e-01, 4.77546826e-02, 1.57271561e-02,
       7.20157843e-02, 3.50213745e-02, 4.00000000e-01, 4.62500000e-01,
       3.12500000e-01, 3.25000000e-01, 3.81982719e-01, 5.23601144e-01,
       3.90681658e-01, 4.13183449e-01, 8.16836058e-01, 1.02842555e-01,
       8.04762992e-02, 7.77704702e-02, 5.09700756e-02, 4.75000000e-01,
       5.00000000e-01, 3.62500000e-01, 5.00000000e-01, 3.99245906e-01,
       5.76967216e-01, 4.10557720e-01, 4.01150517e-01, 8.10207689e-01,
       1.19900623e-01, 5.81088901e-02, 1.18710950e-01, 1.52581388e-01])

In [11]:
temp = []
a = np.array([1,2,3])
b = np.array([4,5,6])
temp.append(a)
temp.append(b)
temp = np.array(temp)
temp

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
stock_id = "2330"
start_date='2013-01-01'
end_date='2020-12-31'

# 股價日成交資訊
df = api.taiwan_stock_daily(
    stock_id = stock_id,
    start_date = start_date,
    end_date = end_date
)

#df
#dateArray = TaiwanStockPriceDay['date']
len(dateArray[dateArray > '2012-12-31'])

1962

In [20]:
df2 = pd.read_csv('./data/input.csv',header=None)
df2

,0,1,2,3,4,5,6,7,8,9,...,250,251,252,253,254,255,256,257,258,259
0,0.487500,0.525000,0.287500,0.450000,0.599061,0.744000,0.287843,0.438358,0.859368,0.121258,...,0.500000,0.399246,0.576967,0.410558,0.401151,0.810208,0.119901,0.058109,0.118711,0.152581
1,0.200000,0.483019,0.200000,0.460377,0.800000,0.768000,0.305565,0.439413,0.868537,0.229137,...,0.766038,0.571128,0.659106,0.458786,0.401705,0.876381,0.148143,0.056829,0.287077,0.024170
2,0.362162,0.386486,0.321622,0.362162,0.593153,0.750000,0.288777,0.438437,0.869311,0.176722,...,0.718919,0.762744,0.692635,0.445940,0.371332,0.891516,0.212834,0.114300,0.152253,0.084841
3,0.402703,0.516216,0.402703,0.483784,0.649702,0.787234,0.319720,0.397905,0.978458,0.158701,...,0.759459,0.687089,0.706407,0.502844,0.348612,0.892399,0.221259,0.160350,0.038474,0.031240
4,0.467568,0.475676,0.354054,0.354054,0.551898,0.699346,0.328584,0.421417,0.927419,0.134040,...,0.678378,0.731326,0.657620,0.534817,0.343493,0.883120,0.175344,0.177580,0.033377,0.152088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1957,0.294382,0.355056,0.280899,0.314607,0.289395,0.684848,0.244989,0.690310,0.219399,0.130341,...,0.597753,0.200000,0.592014,0.591770,0.643815,0.044189,0.056853,0.042118,0.007394,0.003124
1958,0.368539,0.375281,0.200000,0.200000,0.800000,0.676647,0.234562,0.747625,0.199293,0.704891,...,0.611236,0.200000,0.615307,0.595259,0.654660,0.044079,0.029277,0.006279,0.000000,0.069056
1959,0.286747,0.293976,0.200000,0.293976,0.524524,0.689655,0.219102,0.728335,0.202276,0.150609,...,0.655422,0.287426,0.630747,0.594247,0.637693,0.042422,0.081357,0.045588,0.007234,0.002960
1960,0.314286,0.323810,0.200000,0.304762,0.800000,0.715789,0.097127,0.698649,0.206805,0.287847,...,0.609524,0.296319,0.630735,0.543877,0.629222,0.042311,0.089789,0.061769,0.053571,0.068070
1961,0.290000,0.290000,0.200000,0.240000,0.548607,0.688172,0.110415,0.686273,0.205700,0.136062,...,0.800000,0.688766,0.679463,0.580322,0.622256,0.052696,0.218049,0.115009,0.042749,0.000493