In [1]:
import pandas as pd
import numpy as np
import math
import csv

from FinMind.data import DataLoader
import talib

from mplfinance.original_flavor import candlestick_ohlc
import matplotlib.dates as mpl_dates
import matplotlib.pyplot as plt

from datetime import datetime
from io import StringIO
import pprint as pp


api_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRlIjoiMjAyMS0xMi0yNyAxNDo1OTowOSIsInVzZXJfaWQiOiJkdXJhbnQ3MTA5MTYiLCJpcCI6IjE0MC4xMjAuMTMuMjMwIn0.8-KIC3-OA4D6JcOtQ_fJBOVkyugx60t1Gy82c57TLz4"

api = DataLoader()
api.login_by_token(api_token = api_token)

In [5]:
stock_list = ['2330', '2603', '2002','1301', '2801']
#stock_list = ['2330']

start_date = '2003-11-17'
end_date = '2021-12-31'

In [6]:
for stock_id in stock_list:
    print(stock_id)
    # 股價日成交資訊
    TaiwanStockPriceDay = api.taiwan_stock_daily(
        stock_id = stock_id,
        start_date = start_date,
        end_date = end_date
    )



    # 融資融券表
    TaiwanStockMarginPurchaseShortSale = api.taiwan_stock_margin_purchase_short_sale(
        stock_id = stock_id,
        start_date = start_date,
        end_date = end_date
    )
    
    TaiwanStockPriceDay['ratio'] = TaiwanStockMarginPurchaseShortSale['ShortSaleTodayBalance'] / TaiwanStockMarginPurchaseShortSale['MarginPurchaseTodayBalance']
    #print(TaiwanStockPriceDay)
    print('===============================')

    
    # 加權指數
    TaiwanStockTotalReturnIndex = api.taiwan_stock_total_return_index(
        index_id="TAIEX",
        start_date = start_date,
        end_date = end_date
    )

    #print(TaiwanStockTotalReturnIndex)


    dateArray = TaiwanStockPriceDay['date']
    
    piece = TaiwanStockPriceDay.iloc[:][['open', 'max', 'min', 'close','Trading_Volume']]
    piece['TAIEX'] = TaiwanStockTotalReturnIndex.iloc[:][['price']]
    #print(piece)
    piece = np.array(piece)
    np.savetxt('all_stock/' + stock_id + '.csv', piece, delimiter=",")

2330
===============================
2603
===============================
2002
===============================
1301
===============================
2801
===============================

In [4]:
TaiwanStockPriceDay

,date,stock_id,Trading_Volume,Trading_money,open,max,min,close,spread,Trading_turnover
0,2003-11-17,2330,24971617,1655044104,67.0,67.0,65.5,66.5,-1.0,5941
1,2003-11-18,2330,33040991,2186185656,65.5,67.0,65.5,67.0,0.5,4489
2,2003-11-19,2330,25690318,1696943046,66.0,66.5,65.5,66.0,-1.0,4299
3,2003-11-20,2330,41680480,2722307580,65.5,66.0,64.5,65.5,-0.5,7604
4,2003-11-21,2330,47819573,3095856062,65.0,65.0,64.0,65.0,-0.5,8027
...,...,...,...,...,...,...,...,...,...,...
4474,2021-12-24,2330,12008673,7276331245,606.0,609.0,604.0,604.0,-2.0,10444
4475,2021-12-27,2330,16771900,10193462167,604.0,610.0,604.0,606.0,2.0,16637
4476,2021-12-28,2330,35156339,21569506434,610.0,615.0,610.0,615.0,9.0,36241
4477,2021-12-29,2330,25604320,15788043027,615.0,619.0,614.0,616.0,1.0,28804
4478,2021-12-30,2330,20522055,12654016133,619.0,620.0,615.0,615.0,-1.0,15565